// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Data.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    partial class ForumAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumApp.Data.DataModels.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f0b33f9-8b00-4021-95c1-cac7332b8462"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras placerat vitae quam sed egestas. Pellentesque lobortis felis quam, quis rhoncus.",
                            Title = "My First Post"
                        },
                        new
                        {
                            Id = new Guid("00c7933e-49f2-413e-add8-acdcfb77ec4e"),
                            Content = "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...",
                            Title = "My Second Post"
                        },
                        new
                        {
                            Id = new Guid("117529d9-f60f-46e6-950c-2bd28e4c45da"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse aliquam, ante id sagittis interdum, mi diam lobortis nibh, ac varius magna ex a erat. Praesent pharetra justo vel ante blandit, ac tempus leo lacinia. Pellentesque iaculis quis arcu ut rutrum. Mauris sagittis maximus neque. Sed scelerisque turpis non magna dapibus",
                            Title = "My third Post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
